### ISSUE TITLE
Add documentation on how to run DST Maker to its README

### ISSUE THREAD

**Issue by JeremyMcCormick** [JeffersonLab/hps-dst#40]
It would be nice to consolidate the information about running this tool from the Confluence:

https://confluence.slac.stanford.edu/display/hpsg/ROOT+DST+Maker+Instructions

e.g. copy the entire section under "Generating DST Files from LCIO" into this project's README.

Then the Confluence page would not really be needed and could be archived or deleted.

**Comment by omar-moreno** [comment]
I won't be able to get this done anytime soon so I'm assigning this to @JeremyMcCormick.

**Comment by JeremyMcCormick** [comment]
Okay will do.

**Comment by JeremyMcCormick** [comment]
By the way, does the project's README duplicate this information?

https://confluence.slac.stanford.edu/display/hpsg/Installing+the+DST+Tools

I would be inclined to make sure these are both in sync with each other and then delete the Confluence version, if in fact these duplicate each other.  Then we could just link to the github page instead.
