### ISSUE TITLE
Implement install step in CMake build

### ISSUE THREAD

**Issue by JeremyMcCormick** [JeffersonLab/hps-dst#43]
The binary and libraries should be installed to bin and lib respectively in an install step within the CMakeLists.txt config file.

**Comment by mholtrop** [comment]
Should really instead revamp the CMakeFiles.txt stuff to use the ROOT supplied cmake files so that the dictionary is properly created during build and not during configure. 

Since I have done something similar recently, perhaps I should do this?

**Comment by mholtrop** [comment]
There are further issues with the current cmake scheme. It doesn't build at JLab with the root6.06 and gcc4.9.
ERROR:
CMake Error at /u/apps/cmake/cmake-3.5.1/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find ROOT (missing: ROOT_INCLUDE_DIRS)
Call Stack (most recent call first):
  /u/apps/cmake/cmake-3.5.1/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindROOT.cmake:299 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:29 (find_package)

The currently used FindROOT is too old.

**Comment by omar-moreno** [comment]
We had this working with ROOT 6 at JLab before, what changed?

I agree that the main CMakeLists file should be updated such that the
dictionary is generated at build time.  If you decide to do this, please
make sure that everything compiles correctly on Linux and that the changes
you make are compatible with ROOT 5.

**Comment by mholtrop** [comment]
New version on the branch seems fully functional but requires ROOT to be compiled with cmake, which is now the default for ROOT.

Tested with:
Centos 6 +  ROOT 5 or ROOT 6
Centos 7 +  ROOT 5 or ROOT 6
Mac OS X + ROOT 5 or ROOT 6
JLAB       + Only ROOT 6 currently available with cmake. ROOT 5 forthcoming.

I plan to merge next week after completing testing with new JLab root installations.

**Comment by mholtrop** [comment]
Tested at JLAB agains patched LCIO "trunk" for ROOT6 and patched LCIO v02-06 for ROOT5

I consider this complete and will merge with trunk soon unless I hear a complaint.

**Comment by mholtrop** [comment]
merged.
