### ISSUE TITLE
Multiple copies of EcalHit written if hit shared by multiple clusters.

### ISSUE THREAD

**Issue by mholtrop** [JeffersonLab/hps-dst#44]
Since the EcalHit objects are written from the clusters, the hits can be written more than once if they appear in more than one cluster. The solution is to make a lookup map, as is done for SVT hits.

Fix already in testing stage.

**Comment by mholtrop** [comment]
Fixed and merged into "master".

**Comment by mholtrop** [comment]
Collection name changed. New version will:
A) Test to see of the TimeCorrEcalHits exist in the lcio file. If it does, use it, if it does not, fall back to EcalCalHits.
B) Use an std::pair<int,int> for the map key, with the first int the id0 of the hit and the second int 10*getTime(). This should uniquely identify any hit.

**Comment by omar-moreno** [comment]
This issue was resolved as of commit 13a42af09f84738aaec2b5fbc3ab9527682db2af.
