### ISSUE TITLE
Add uncorrected cluster collection to DST output

### ISSUE THREAD

**Issue by JeremyMcCormick** [JeffersonLab/hps-dst#45]
The LCIO collection containing clusters with uncorrected energies should be added to the DST output.  It should be written by the standard EngRun recon config and available in the "EcalClusters" collection in the LCIO file.

**Comment by hszumila** [comment]
Separately, we also need to output the GTP clusters as these are used for trigger studies. These would have the same format, but it is a separate cluster collection. Currently, the GTP clusters are not persisted in the LCIO output files, so we should change that in the steering file for the future, but the DSTs should write this also, if available, from the LCIO file.

**Comment by JeremyMcCormick** [comment]
Thanks Holly.  I will add a separate task for this.
