### ISSUE TITLE
Write GTP clusters to DST output if collection exists

### ISSUE THREAD

**Issue by JeremyMcCormick** [JeffersonLab/hps-dst#46]
The collection containing reconstructed GTP clusters should be written to the DST output, if it exists in the input LCIO file.

This is currently not in the LCIO output from reconstruction but is planned to be added.

https://jira.slac.stanford.edu/browse/HPSJAVA-696

In the past, the GTP cluster collection has been called "EcalClustersGTP".

**Comment by omar-moreno** [comment]
@hszumila @JeremyMcCormick I'll hold off on adding this collection until I have a file to test against.  I don't want to introduce unecessary bugs.

**Comment by JeremyMcCormick** [comment]
Yes, I agree.  This issue depends on that JIRA item getting resolved first.  I just wanted to put it here so we don't forget about it.
