### ISSUE TITLE
Add pointers between different vertex constraints

### ISSUE THREAD

**Issue by hszumila** [JeffersonLab/hps-dst#48]
It should be possible to access the different constraint values between the different vertex candidate collections. For example, it should be possible to compare the UNC and BSC chi2 values and the z vertex positions.

**Comment by mholtrop** [comment]
With the current version of the LCIO output from MOUSE, the three types of constraint: UNC_V0, BSC_V0 and TC_V0 are always all written in the same order. You can thus get the first from one collection, and it will correspond to the one from the other collections.  So pointer references are no longer needed.

If you are nervous, and want to check that this is indeed the case (esp. for older files), the you can get the particles from the collections and check whether the daughters are the same.
