### ISSUE TITLE
Remove check for partial tracks collection

### ISSUE THREAD

**Issue by omar-moreno** [JeffersonLab/hps-dst#59]
Currently, the SVT data writer loops through all available track collections and writes all tracks to the DST except those considered to be partial tracks.  Avoiding writing these tracks required a check for the partial tracks collection.  However,  the latest pass will no longer generate a collection of particle tracks so this requirement can be removed.

@mdiamon @sebouh137

**Comment by sebouh137** [comment]
what do you mean by "particle tracks"?   Do you mean the tracks and gbl_tracks collections inside the dst root files?

**Comment by omar-moreno** [comment]
This issue is resolved by commit 2a4f4600d2290327717e55ce862ba745815ca875.
