### ISSUE TITLE
only GBLTracks should need TrackState@ECal and TrackData

### ISSUE THREAD

**Issue by mdiamon** [JeffersonLab/hps-dst#65]
New version of hps-java creates TrackState@Ecal and TrackData only for GBLTracks, since no one needs this stuff for MatchedTracks anymore.  Currently, SvtDataWriter throws exception if _any_ track is missing this stuff; SvtDataWriter should only throw exception if a GBLTrack is missing this stuff.

**Comment by omar-moreno** [comment]
This issue was resolved by PR #68.
