### ISSUE TITLE
Update DST To reflect new MOUSE objects

### ISSUE THREAD

**Issue by mholtrop** [JeffersonLab/hps-dst#69]
To stay relevant, DST needs to contain the new collections created with the pass2 processing of the 2016 data set.

**Comment by omar-moreno** [comment]
I don't think it's worth updating this version of the DST maker when the
rewrite is nearly finished.  I'm hoping we depecrate this whole package
within the next two weeks.

**Comment by mholtrop** [comment]
OK.

**Comment by mholtrop** [comment]
I now think that it is worth it. The dst-maker is still relevant.

**Comment by mholtrop** [comment]
Included in merge #74
